#!/usr/bin/env zsh

set -e  # Exit immediately if a command exits with a non-zero status

# Define paths
CITADEL_CLI_DIR="/Users/jchilders/work/jchilders/citadel_cli"
IMPORTING_DIR="/Users/jchilders/work/jchilders/vite_tailwind_react/project_b"

# Build and link citadel_cli
cd "$CITADEL_CLI_DIR"
echo "-=-=> Building ..."
npm run build
echo "-=-=> Linking ..."
npm link

# Build and link citadel_cli in the importing project
cd "$IMPORTING_DIR"
# echo "Building project_b..."
# npm run build
echo "-=-=> Linking in project_b..."
npm link citadel_cli

# Start the Vite development server
echo "-=-=> Starting development server..."
npm run start
