/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{js,ts,jsx,tsx}',],
  // Tailwind classes to pre-compile into our component's standalone CSS bundle.
  // This means apps which use this component don't have to be using Tailwind.
  // This list is automatically maintained by extract-classes.js
  safelist: [
  "absolute",
  "animate-spin",
  "bg-gray-100",
  "bg-gray-800",
  "bg-gray-900",
  "bg-green-500",
  "bg-red-500",
  "bg-white",
  "border",
  "border-2",
  "border-gray-300",
  "border-gray-700",
  "border-t-gray-600",
  "flex",
  "flex-1",
  "flex-col",
  "flex-shrink-0",
  "flex-wrap",
  "font-mono",
  "gap-2",
  "h-4",
  "h-auto",
  "h-full",
  "inline-block",
  "items-center",
  "justify-center",
  "last:mb-0",
  "last:mr-0",
  "max-h-[300px]",
  "max-w-[400px]",
  "mb-4",
  "min-h-0",
  "min-h-screen",
  "ml-2",
  "mr-2",
  "mt-1",
  "my-2",
  "object-contain",
  "overflow-y-auto",
  "p-3",
  "p-4",
  "p-6",
  "pointer-events-none",
  "pt-3",
  "px-2",
  "px-4",
  "py-1",
  "relative",
  "rounded",
  "rounded-full",
  "rounded-lg",
  "shadow-lg",
  "text-blue-400",
  "text-gray-200",
  "text-gray-400",
  "text-gray-500",
  "text-gray-700",
  "text-left",
  "text-red-400",
  "text-sm",
  "text-white",
  "top-0",
  "underline",
  "w-4",
  "w-full",
  "whitespace-pre"
],
  theme: {
    extend: {
      animation: {
        'slide-up': 'slideUp 0.2s ease-out',
        'slide-down': 'slide-down 150ms ease-out forwards',
      },
      keyframes: {
        slideUp: {
          '0%': { transform: 'translateY(100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        'slide-down': {
          '0%': { transform: 'translateY(0)' },
          '100%': { transform: 'translateY(100%)' },
        },
      },
    },
  },
  plugins: [],
}
