name: Auto Publish

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tailwind.config.js'
      - 'tsconfig.json'
      - 'webpack.config.js'
      - 'vite.config.ts'
      - '!src/test/**'
      - '!src/__test-utils__/**'
      - '!src/**/__tests__/**'
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml
    
  publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
      - name: Bump version and publish
        run: |
          set -euo pipefail

          CURRENT_VERSION=$(node -p "require('./package.json').version")
          IFS='.' read -r major minor patch <<<"$CURRENT_VERSION"

          while true; do
            patch=$((patch + 1))
            CANDIDATE_VERSION="$major.$minor.$patch"

            if git rev-parse --verify "refs/tags/v$CANDIDATE_VERSION" >/dev/null 2>&1; then
              echo "Tag v$CANDIDATE_VERSION already exists; bumping patch again."
              continue
            fi

            break
          done

          echo "Bumping version to $CANDIDATE_VERSION"
          npm version "$CANDIDATE_VERSION" --no-git-tag-version

          git add package.json package-lock.json
          git commit -m "chore: release v$CANDIDATE_VERSION"
          git tag -a "v$CANDIDATE_VERSION" -m "v$CANDIDATE_VERSION"

          git push --follow-tags
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
